services:
  frontend:
    build: .
    ports:
      - 8080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app:delegated

  mysql:
    image: mysql:5.7
    secrets:
      - mysql_root
      - mysql_user
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root
      - MYSQL_DATABASE=costsplitting
      - MYSQL_USER=costsplitting
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_user
    

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    environment:
      - ADMINER_DEFAULT_SERVER=mysql

secrets:
  mysql_root:
    file: ./mysql_root.txt
  mysql_user:
    file: ./mysql_user.txt
