#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */
use codemix\yii2confload\Config;

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = Config::bootstrap(__DIR__);

$application = Yii::createObject('yii\console\Application', [$config->console()]);
$exitCode = $application->run();
exit($exitCode);