<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Contact' => 'Kontakt',
    'If you have business inquiries or other questions, please fill out the following form to contact us.' => 'Wenn Sie geschäftliche oder sonstige Anfragen haben, füllen Sie diese Formular aus, um un szu kontaktieren.',
    'Return to home page' => 'Zurück zur Home-Seite',
    'Submit' => 'Senden',
    'Thank you for contacting us.' => 'Vielen Dank für Ihre Kontaktanfrage.',
    'Thank you.' => 'Vielen Dank.',
    'We will respond to you as soon as possible.' => 'Wir werden Ihnen so bald wie möglich antworten.',
    'Email' => 'E-Mail',
    'Message' => 'Nachricht',
    'Subject' => 'Betreff',
    'Verification Code' => 'Überprüfungs-Code',
    'Your Name' => 'Ihr Name',
    'Click on the code to get another one' => 'Klicken Sie auf den Code, um einen anderen zu erhalten'
];
