<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Exchange Rate' => 'Umtauschkurs hinzufügen',
    'Are you sure you want to delete this item?' => 'Wollen Sie diesen Eintrag wirklich löschen?',
    'CSV File' => 'CSV-Datei',
    'Delete' => 'Löschen',
    'Exchange Rates' => 'Umtauschkurse',
    'Failed to open the CSV file.' => 'Konnte die CSV-Datei nicht öffnen',
    'Import EZB Data' => 'EZB-Daten importieren',
    'Reset' => 'Zurücksetzen',
    'Save' => 'Speichern',
    'Search' => 'Suche',
    'The CSV file does not exist.' => 'Die CSV-Datei existiert nicht.',
    'Truncate Table' => 'Tabelle leeren',
    'Update' => 'Ändern',
    'Create Exchangerate' => '',
    'Exchangerates' => '',
    'Import Exchange Rates File' => '',
    'The requested currency is not allowed.' => '',
    'The requested page does not exist.' => '',
    'Update Exchangerate: {name}' => '',
    'Update Exchange Rate: {name}' => '@@Umtauschrate ändern: {name}@@',
];
